### ISSUE TITLE
Feature Request: Remember IP Address

### ISSUE THREAD

**Issue by blumpcus** [MrKonstantinSh/OpenScreen#1]
Hi there,

Thanks for making OpenScreen, it's exactly what I've been looking for and suits my minimalist needs quite well.

I just have a quick question/feature request: 
Is there anyway to save the IP Address without having to type it in every time I open the program?
Whether it's saved in the GUI or in a config file that it reads, whatever would be easiest to achieve.

Thanks a lot for building this, going straight into my preferred tools list.

**Comment by MrKonstantinSh** [comment]
Hi, @blumpcus

I added the function you requested.

Now if the `"Remember IP Address and Port"` field is checked, the IP address and port will be saved and they will be restored on the next program launches.

Link to installer with updated app: [OpenScreen-Installer.msi](https://github.com/MrKonstantinSh/OpenScreen/releases/download/v1.2/OpenScreen-Installer.msi)
Link to new release: [OpenScreen v1.2](https://github.com/MrKonstantinSh/OpenScreen/releases/tag/v1.2)

PS. I'm very pleased that my project was useful to someone. 😄

**Comment by blumpcus** [comment]
I just wanted to say thank you so much for considering this function, adding it, and doing it within 24 hours of my request. 
That was very generous of you, I really appreciate it. 

My friends and I are officially using this tool and getting great use out of it =)
