### ISSUE TITLE
Unsupported by VS

### ISSUE THREAD

**Issue by Dontmindmes** [MrKonstantinSh/OpenScreen#2]
Hey i downloaded and attempted to open the project but got this error
https://i.imgur.com/XWqWhpO.png

**Comment by MrKonstantinSh** [comment]
Hi @Dontmindmes! Sorry for delay.

This error occurred during solution migration. The OpenScreen.Installer.vdproj project (the OpenScreen installer) uses the "Microsoft Visual Studio Installer Project" extension. Install it in Visual Studio to work correctly with this project.
